---
- name: Check OpenVPN Certificates Expiration
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Find all certificates in /etc/openvpn
      find:
        paths: "/etc/openvpn"
        patterns: "*.crt"
      register: cert_files

    - name: Get certificate expiration date
      command: "openssl x509 -enddate -noout -in {{ item.path }}"
      register: cert_expiry
      loop: "{{ cert_files.files }}"
      changed_when: false
      ignore_errors: yes

    - name: Convert certificate expiration date to epoch
      shell: |
        date -d "$(echo {{ item.stdout }} | sed 's/notAfter=//')" +%s
      register: cert_expiry_epoch
      loop: "{{ cert_expiry.results }}"
      changed_when: false
      ignore_errors: yes

    - name: Check if certificates are expiring soon
      debug:
        msg: "Certificate {{ item.item.path }} expires on {{ item.stdout | regex_replace('notAfter=', '') }}"
      loop: "{{ cert_expiry_epoch.results }}"
      when: "(item.stdout | int) - (ansible_date_time.epoch | int) < (30 * 86400)"
