---
- name: Check OpenVPN Certificates Expiration
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Find all certificates in /etc/openvpn
      find:
        paths: "/etc/openvpn"
        patterns: "*.crt"
      register: cert_files

    - name: Get certificate expiration date
      command: "openssl x509 -enddate -noout -in {{ item.path }}"
      register: cert_expiry
      loop: "{{ cert_files.files }}"
      changed_when: false
      ignore_errors: yes

    - name: Extract and format expiration date
      set_fact:
        cert_expiry_dates: "{{ cert_expiry.results | map(attribute='stdout') | list }}"

    - name: Check if certificates are expiring soon
      debug:
        msg: "Certificate {{ item.item.path }} expires on {{ item.stdout | regex_replace('notAfter=', '') }}"
      loop: "{{ cert_expiry.results }}"
      when: "(item.stdout | regex_replace('notAfter=', '') | strftime('%s') | int) - (ansible_date_time.epoch | int) < (30 * 86400)"
