---
- name: Check OpenVPN certificates for near expiration
  hosts: localhost
  gather_facts: no
  collections:
    - community.crypto
  vars:
    # Define the directory containing certificates
    cert_dir: /etc/openvpn
    # Define the expiration threshold (in days)
    expiration_threshold: 30

  tasks:
    - name: Find all certificate files in the directory
      find:
        paths: "{{ cert_dir }}"
        patterns: "*.crt,*.pem"
        recurse: yes
      register: cert_files

    - name: Check each certificate for expiration
      community.crypto.x509_certificate_info:
        path: "{{ item.path }}"
      loop: "{{ cert_files.files }}"
      register: cert_info
      ignore_errors: yes  # Continue even if some certificates are invalid

    - name: Display certificates near expiration
      debug:
        msg: |
          Certificate: {{ item.item.path }}
          Expiration Date: {{ item.not_after }}
          Days Remaining: {{ ((item.not_after | to_datetime) - (ansible_date_time.iso8601 | to_datetime)).days }}
          Status: {{ 'Expired' if ((item.not_after | to_datetime) - (ansible_date_time.iso8601 | to_datetime)).days < 0 else 'Near Expiration' if ((item.not_after | to_datetime) - (ansible_date_time.iso8601 | to_datetime)).days <= expiration_threshold else 'Valid' }}
      loop: "{{ cert_info.results }}"
      when: item is not skipped
      loop_control:
        label: "{{ item.item.path }}"
